#!/usr/bin/env bash

echo "Generating reltime.rb cask file..."

TARGET_DIR="${1}"
shift || true

if [[ ! -d "${TARGET_DIR}" ]]; then
  echo "Error: TARGET_DIR '${TARGET_DIR}' does not exist or is not a directory." >&2
  exit 1
fi

TARGET_FILENAME="reltime.rb"
TARGET_FULLPATH="${TARGET_DIR}/${TARGET_FILENAME}"

if [[ ! -z "${GITHUB_OUTPUT}" ]]; then
  (
    echo "target_name=reltime"; 
    echo "target_path=${TARGET_FULLPATH}";
    echo "target_filename=${TARGET_FILENAME}";
  ) >> "${GITHUB_OUTPUT}"
fi

VERSION="${VERSION:-${GITHUB_REF##*/}}"

SHA_DARWIN_ARM64="$(sha256sum artifacts/archives/reltime_darwin_arm64.tar.gz | awk '{print $1}')"
SHA_DARWIN_AMD64="$(sha256sum artifacts/archives/reltime_darwin_amd64.tar.gz | awk '{print $1}')"
SHA_LINUX_ARM64="$(sha256sum artifacts/archives/reltime_linux_arm64.tar.gz | awk '{print $1}')"
SHA_LINUX_AMD64="$(sha256sum artifacts/archives/reltime_linux_amd64.tar.gz | awk '{print $1}')"

tee "${TARGET_FULLPATH}" << EOF
# This file was generated by generate_homebrew_cask.sh. DO NOT EDIT.
cask "reltime" do
  name "reltime"
  desc "Relative Time is a command-line utility that provides human-readable time differences."
  homepage "https://github.com/na4ma4/relative-time"
  version "${VERSION}"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "reltime"

  on_macos do
    on_intel do
      sha256 "${SHA_DARWIN_AMD64}"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_DARWIN_ARM64}"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "${SHA_LINUX_AMD64}"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "${SHA_LINUX_ARM64}"
      url "https://github.com/na4ma4/relative-time/releases/download/#{version}/reltime_linux_arm64.tar.gz"
    end
  end

  postflight do
    if OS.mac?
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/reltime"]
    end
  end

  # No zap stanza required
end
EOF

echo "Generated reltime.rb"
